#!/bin/sh

# Check for git repo
git rev-parse --short HEAD > /dev/null || exit 1

# Usage: branch [QUERY]
# QUERY can omited.

# Pick a branch with fzf, sorted by commited date.
git for-each-ref --sort=-committerdate \
	--format='%(refname:short)' 'refs/heads/**' 'refs/remotes/**' \
	| sed 's|^origin/||' | fzf --no-sort --query="$@"
