#!/bin/sh

# Check for git repo
git rev-parse --short HEAD > /dev/null || exit 1

# Usage: branch [QUERY]
# [QUERY] can omitted.

# Pick a branch with fzf, sorted by commited date.
git branch --sort=-committerdate \
	--format='%(align:50,left)%(refname:short)%(end) %(contents:subject)'\
	--color=always\
	| fzf --nth=1 --no-sort --query="$@"\
	| cut -d' ' -f1
